config/routes.rb
Rails.application.routes.draw do
  resources :users
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles      # only: [:show, :index, :new, :create, :edit, :update, :distroy // No need because 
                                                                                            # we mentioned all methods
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true, length: {minimum: 6, maximum: 50}
    validates :description, presence: true, length: {minimum: 20, maximum: 100}
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    before_save {self.email = email.downcase}

    validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 105 }
    
    VALID_EMAIL_REGEX =  /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    
    validates :email, presence: true, 
                      uniqueness: { case_sensitive: false }, 
                      length: { maximum: 105 },
                      format: { with: VALID_EMAIL_REGEX }
    has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    def show
        @article = Article.find(params[:id])
    end

    def index
        @articles = Article.all
    end

    def new
        @article = Article.new
    end

    def edit
        @article = Article.find(params[:id])
    end

    def create
        @article = Article.new(params.require(:article).permit(:title, :description))
        if @article.save
            #redirect_to article_path(@article) s
            flash[:notice] = "Article was created succesfully."
            redirect_to  @article     #// This will also have same effect.
        else 
            render 'new'
        end
    end

    def update
        @article = Article.find(params[:id])
        if @article.update(params.require(:article).permit(:title, :description))
            flash[:notice] = "Article was updated succesfully."  #// <%= flash[:notice]%> Has to be added to rendered template.
            redirect_to @article
        else
            render 'edit'
        end
    end

    def destroy
        @article = Article.find(params[:id])
        @article.destroy!
        redirect_to articles_path
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        
    end

    def about
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/edit.html.erb
<h1> Edit The Article </h1>
<%= flash[:notice]%>

<% if @article.errors.any? %>
    <h2>Following Errors Occured</h2>
    <ul>
        <%@article.errors.full_messages.each do |msg|%>
             <li>  <%= msg %>  </li>
        <%end%>
    </ul>
<% end %>

<%= form_with(model: @article, local: true) do |f| %>

<p>
    <%= f.label :title%><br/>
    <%= f.text_field :title %>
</p>
<p>
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
</p>
<p>
    <%= f.submit %>
</p>

<% end %>

app/views/articles/index.html.erb
<h1> Articles Listing Page</h1>

<table> 
    <thead>
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th colspan = "3" >Actions</th>
        </tr>
    </thead>

    <tbody>
        <%@articles.each do |article| %>
            <tr>
                <td> <%=article.title%> </td>
                <td>  <%=article.description%> </td>
                <td> <%= link_to 'SHOW', article_path(article) %> </td>
                <td> <%= link_to 'EDIT', edit_article_path(article) %> </td>
                <td> <%= button_to 'DELETE', article_path(article), method: :delete, :onclick=> "return confirm('Are you sure you want to delete this item?')" %> </td>
            </tr>
        <% end %>
    </tbody>
</table>

<%= link_to 'CREATE NEW ARTICLE', new_article_path %>

app/views/articles/new.html.erb
<h1> Creating New Article </h1>

<% if @article.errors.any? %>
    <h2>Following Errors Occured</h2>
    <ul>
        <%@article.errors.full_messages.each do |msg|%>
             <li>  <%= msg %>  </li>
        <%end%>
    </ul>
<% end %>

<%= form_with scope: :article, url: articles_path, local: true do |f| %>

<p>
    <%= f.label :title%><br/>
    <%= f.text_field :title %>
</p>
<p>
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
</p>
<p>
    <%= f.submit %>
</p>

<% end %>

<%= link_to "RETURN TO LISTING", articles_path %>

app/views/articles/show.html.erb
<h1> Showing article details</h1>
<%= flash[:notice]%>
<p> <strong> Title : </strong> <%= @article.title %></p>
<p> <strong> Description : </strong> <%= @article.description %></p>

<%= link_to "EDIT", edit_article_path(@article) %> 
<%= button_to "DELETE", article_path(@article), method: :delete, :onclick=> "return confirm('Are you sure you want to delete this item?')" %>
<%= link_to "RETURN TO LISTING", articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# <%= stylesheet_link_tag "application.bootstrap", "data-turbo-track": "reload" %> %>
    <%= javascript_include_tag "turbo", type: "module" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">ALPHA BLOG</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Welcome to about page</h1>
<%= link_to "RETURN TO LISTING", articles_path %>
<%= link_to "HOME", root_path %>

app/views/pages/home.html.erb
<h1> Welcome To Alpha Blog !</h1>

<%= link_to "ARTICLE LISTING", articles_path %>
<%= link_to "ABOUT PAGE", about_path %>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Username:</strong>
    <%= user.username %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>